name: Pull Requests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.17.0
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
          cache: npm
      - name: Install Dependencies  
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run test suite
        run: npm run test